version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.3.1

jobs:
  setup:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: Install PyYaml
          command: |
            pip install -r requirements.txt
      - run:
          name: Generate Config
          command: |
            python generate-config.py > generated-config.yml
      - persist_to_workspace:
          root: .
          paths:
            - generated-config.yml
            
workflows:
  set-up:
    jobs:
      - setup
      - continuation/continue:
          requires:
            - setup
          pre-steps:
            - attach_workspace:
                at: .
          configuration_path: generated-config.yml