version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  configure-role-arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-credentials-setup
      - run: |
          echo PIPELINE_ROLE_ARN

commands: 
  aws-credentials-setup:
    # executor: aws-cli/default
    parameters:
      role-arn:
        type: string
        default: PIPELINE_ROLE_ARN
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circleci
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION
      - aws-cli/role-arn-setup:
          profile-name: friction-pipeline
          role-arn: << parameters.role-arn >>
          source-profile: circleci
workflows:
  aws-cli:
    jobs:
      - configure-role-arn:
          context: FlatForce Context