version: 2.1

jobs:
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - aws-credentials-setup
      - run:
          aws lambda list-functions
          

commands: 
  aws-credentials-setup:
    parameters:
      role-arn:
        type: string
        default: $PIPELINE_ROLE_ARN
    steps:
      - checkout
      - run: |
          read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \<<< \
            $(aws sts assume-role-with-web-identity \
            --role-arn "<< parameters.role-arn >>" \
            --role-session-name "CircleCI-${CIRCLE_WORKFLOW_ID}-${CIRCLE_JOB}" \
            --web-identity-token $CIRCLE_OIDC_TOKEN \
            --duration-seconds 3600 \
            --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
            --output text)
          export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
workflows:
  aws-cli:
    jobs:
      - deploy:
          context: FlatForce Context